import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>XApi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Test <a href="https://xapi-one.vercel.app/">XApi</a>
        </h1>
        <p>An api to test your project, by <a href='https://marlonfalcon.com'>Marlon</a></p>
      </main>
    </div>
  )
}
